language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
install:
- pip install -U platformio
script:
- platformio --version
- platformio run -e emontx-3phase
    
## Setup auto depoly .hex on release tag
# sudo gem install travis
# cd into repo
# $ travis setup releases
# folow prompts..depoly section will be populated
